### ISSUE TITLE
build error on vite

### ISSUE THREAD

**Issue by himself65** [code-hike/lighter#35]
This is not this project itself issue, but I will find a way to solve the problem and post it here

```shell
/Users/himself65/Library/Caches/fnm_multishells/85522_1705359274939/bin/pnpm run build

> waku-website@0.2.0 build /Users/himself65/Code/waku/packages/website
> waku build --with-ssr

vite v5.0.10 building SSR bundle for production...
src/hooks/index.ts (1:0) Error when using sourcemap for reporting an error: Can't resolve original location of error.
✓ 348 modules transformed.
Unexpected eof (Note that you need plugins to import files that are not JavaScript)
file: /Users/himself65/Code/waku/node_modules/.pnpm/@code-hike+lighter@0.8.1/node_modules/@code-hike/lighter/dist/onig.wasm?module:1:5
1: asm�`���`��`����`�����`�`������`���`��`�������`��������`�`   �������������������``...
        ^
2: 
3:      
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [RollupError]: Unexpected eof
    at error (file:///Users/himself65/Code/waku/node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    ... 6 lines matching cause stack trace ...
    at async ModuleLoader.addModuleSource (file:///Users/himself65/Code/waku/node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/node-entry.js:17760:13) {
  cause: Error [RollupError]: Unexpected eof
      at error (file:///Users/himself65/Code/waku/node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
      at nodeConverters (file:///Users/himself65/Code/waku/node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/parseAst.js:2084:9)
      at convertNode (file:///Users/himself65/Code/waku/node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/parseAst.js:969:12)
      at convertProgram (file:///Users/himself65/Code/waku/node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/parseAst.js:960:48)
      at parseAstAsync (file:///Users/himself65/Code/waku/node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/parseAst.js:2150:20)
      at async Module.tryParseAsync (file:///Users/himself65/Code/waku/node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/node-entry.js:13514:21)
      at async Module.setSource (file:///Users/himself65/Code/waku/node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/node-entry.js:13095:35)
      at async ModuleLoader.addModuleSource (file:///Users/himself65/Code/waku/node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/node-entry.js:17760:13) {
    code: 'PARSE_ERROR',
    pos: 5
  },
  code: 'PARSE_ERROR',
  id: '/Users/himself65/Code/waku/node_modules/.pnpm/@code-hike+lighter@0.8.1/node_modules/@code-hike/lighter/dist/onig.wasm?module',
  pos: 5,
  loc: {
    column: 5,
    file: '/Users/himself65/Code/waku/node_modules/.pnpm/@code-hike+lighter@0.8.1/node_modules/@code-hike/lighter/dist/onig.wasm?module',
    line: 1
  },
  frame: '1: \x00asm\x01\x00\x00\x00\x01�\x01\x16`\x02\x7F\x7F\x01\x7F`\x01\x7F\x01\x7F`\x03\x7F\x7F\x7F\x01\x7F`\x04\x7F\x7F\x7F\x7F\x01\x7F`\x01\x7F\x00`\x05\x7F\x7F\x7F\x7F\x7F\x01\x7F`\x03\x7F\x7F\x7F\x00`\x02\x7F\x7F\x00`\x06\x7F\x7F\x7F\x7F\x7F\x7F\x01\x7F`\x07\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x01\x7F`\x00\x01\x7F`\t\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x01\x7F`\b\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x01\x7F`\x00\x00`\x04...\n' +
    '        ^\n' +
    '2: \x01\x00\x01\x00\x03\x03\x02\x00\x00\x02\x06\x02\x0E\x02\x01\x0F\x01\x01\x01\n' +
    '3: \x13\x02\x05\t\x06\x01\x0E\x14\x15\x10\x07\x03\x02\x01\x00\x01\x04',
  watchFiles: [
    '/Users/himself65/Code/waku/packages/website/src/entries.tsx',
    '/Users/himself65/Code/waku/packages/waku/package.json',
    '/Users/himself65/Code/waku/node_modules/.pnpm/next-mdx-remote@4.4.1_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/next-mdx-remote/rsc.js',
    '/Users/himself65/Code/waku/packages/website/package.json',
    '/Users/himself65/Code/waku/node_modules/.pnpm/next-mdx-remote@4.4.1_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/next-mdx-remote/dist/rsc.js',
    '/Users/himself65/Code/waku/packages/website/src/templates/root-layout.tsx',
    '/Users/himself65/Code/waku/packages/waku/dist/main.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react@18.3.0-canary-c5b937576-20231219/node_modules/react/react.shared-subset.js',
    '/Users/himself65/Code/waku/packages/website/src/templates/blog-article-page.tsx',
    '/Users/himself65/Code/waku/packages/website/src/templates/home-page.tsx',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react@18.3.0-canary-c5b937576-20231219/node_modules/react/cjs/react.shared-subset.production.min.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react@18.3.0-canary-c5b937576-20231219/node_modules/react/cjs/react.shared-subset.development.js',
    '/Users/himself65/Code/waku/packages/waku/dist/router/server.js',
    '/Users/himself65/Code/waku/packages/waku/dist/router/client.js',
    '/Users/himself65/Code/waku/packages/waku/dist/server.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react@18.3.0-canary-c5b937576-20231219/node_modules/react/jsx-runtime.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react@18.3.0-canary-c5b937576-20231219/node_modules/react/cjs/react-jsx-runtime.production.min.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react@18.3.0-canary-c5b937576-20231219/node_modules/react/cjs/react-jsx-runtime.development.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/next-mdx-remote@4.4.1_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/next-mdx-remote/dist/jsx-runtime.cjs',
    '/Users/himself65/Code/waku/packages/waku/dist/client.js',
    '/Users/himself65/Code/waku/packages/waku/dist/router/common.js',
    '/Users/himself65/Code/waku/packages/waku/dist/lib/utils/path.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react@18.3.0-canary-c5b937576-20231219/node_modules/react/jsx-dev-runtime.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-c5b937576-20231219_react-dom@18.3.0-canary-c5b937576-2_4u4q4hpyfvx2kxhzws2c33xndq/node_modules/react-server-dom-webpack/client.edge.js',
    '/Users/himself65/Code/waku/packages/website/src/components/analytics.tsx',
    '/Users/himself65/Code/waku/packages/website/src/components/page.tsx',
    '/Users/himself65/Code/waku/packages/website/src/components/meta.tsx',
    '/Users/himself65/Code/waku/packages/website/src/styles.css',
    '/Users/himself65/Code/waku/packages/website/src/components/providers.tsx',
    '/Users/himself65/Code/waku/packages/website/src/components/mdx.tsx',
    '/Users/himself65/Code/waku/packages/website/src/components/start.tsx',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react@18.3.0-canary-c5b937576-20231219/node_modules/react/cjs/react-jsx-dev-runtime.development.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react@18.3.0-canary-c5b937576-20231219/node_modules/react/cjs/react-jsx-dev-runtime.production.min.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-c5b937576-20231219_react-dom@18.3.0-canary-c5b937576-2_4u4q4hpyfvx2kxhzws2c33xndq/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.development.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react-server-dom-webpack@18.3.0-canary-c5b937576-20231219_react-dom@18.3.0-canary-c5b937576-2_4u4q4hpyfvx2kxhzws2c33xndq/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.edge.production.min.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/react-dom/react-dom.shared-subset.js',
    '/Users/himself65/Code/waku/packages/website/src/atoms/index.ts',
    '/Users/himself65/Code/waku/node_modules/.pnpm/jotai@2.6.1_@types+react@18.2.46_react@18.3.0-canary-c5b937576-20231219/node_modules/jotai/esm/index.mjs',
    '/Users/himself65/Code/waku/packages/website/src/components/menu.tsx',
    '/Users/himself65/Code/waku/packages/website/src/components/credits.tsx',
    '/Users/himself65/Code/waku/packages/website/src/utils/index.ts',
    '/Users/himself65/Code/waku/packages/website/src/components/scroll.tsx',
    '/Users/himself65/Code/waku/packages/website/src/components/fade.tsx',
    '/Users/himself65/Code/waku/node_modules/.pnpm/clsx@2.1.0/node_modules/clsx/dist/clsx.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/@mdx-js+mdx@2.3.0/node_modules/@mdx-js/mdx/index.js',
    '/Users/himself65/Code/waku/packages/website/src/components/code.tsx',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/react-dom/cjs/react-dom.shared-subset.development.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/react-dom/cjs/react-dom.shared-subset.production.min.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/jotai@2.6.1_@types+react@18.2.46_react@18.3.0-canary-c5b937576-20231219/node_modules/jotai/esm/vanilla.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/jotai@2.6.1_@types+react@18.2.46_react@18.3.0-canary-c5b937576-20231219/node_modules/jotai/esm/react.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/@mdx-js+mdx@2.3.0/node_modules/@mdx-js/mdx/lib/compile.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/@mdx-js+mdx@2.3.0/node_modules/@mdx-js/mdx/lib/run.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/@mdx-js+mdx@2.3.0/node_modules/@mdx-js/mdx/lib/core.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/@mdx-js+mdx@2.3.0/node_modules/@mdx-js/mdx/lib/node-types.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/vfile@5.3.7/node_modules/vfile/index.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/@mdx-js+mdx@2.3.0/node_modules/@mdx-js/mdx/lib/evaluate.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/index.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/bright@0.8.4_react@18.3.0-canary-c5b937576-20231219/node_modules/bright/dist/index.mjs',
    '/Users/himself65/Code/waku/packages/website/src/theme.json',
    '/Users/himself65/Code/waku/packages/website/src/hooks/index.ts',
    '/Users/himself65/Code/waku/node_modules/.pnpm/unified@10.1.2/node_modules/unified/index.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/vfile-matter@3.0.1/node_modules/vfile-matter/index.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/render/dom/motion.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/render/dom/motion-minimal.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/vfile@5.3.7/node_modules/vfile/lib/index.js',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/components/LazyMotion/index.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/components/LayoutGroup/index.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/components/MotionConfig/index.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/components/Reorder/index.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/render/dom/features-animation.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/render/dom/features-max.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/value/use-motion-template.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/value/use-motion-value.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/value/utils/resolve-motion-value.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/value/use-transform.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/value/use-spring.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/value/use-scroll.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/value/use-velocity.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/value/scroll/use-element-scroll.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/value/scroll/use-viewport-scroll.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/value/use-time.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/utils/use-motion-value-event.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/utils/reduced-motion/use-reduced-motion.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/utils/reduced-motion/use-reduced-motion-config.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/value/use-will-change/index.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/animation/hooks/use-animate.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/animation/hooks/use-animation.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/utils/use-animation-frame.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/utils/use-cycle.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/animation/interfaces/visual-element.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/components/AnimatePresence/use-presence.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/utils/use-in-view.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/gestures/drag/use-drag-controls.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/events/use-dom-event.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/animation/hooks/animation-controls.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/motion/utils/valid-prop.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/motion/utils/is-motion-component.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/motion/index.mjs',
    '/Users/himself65/Code/waku/node_modules/.pnpm/framer-motion@10.18.0_react-dom@18.3.0-canary-c5b937576-20231219_react@18.3.0-canary-c5b937576-20231219/node_modules/framer-motion/dist/es/motion/utils/unwrap-motion-component.mjs',
    ... 240 more items
  ]
}

Node.js v20.10.0
 ELIFECYCLE  Command failed with exit code 1.

Process finished with exit code 1
```

https://github.com/dai-shi/waku/pull/394

**Comment by hamlim** [comment]
@himself65 I'm starting to look at Waku (noticed that was also linked in your issue description) and ran into this issue as well when using `bright`.

Curious if you found a way around this at all, or have any recommendations?

**Comment by himself65** [comment]
I used shiki after all, they have a [similar api](https://shiki.style/api#codetohast)

https://shiki.style/
